AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15
    Environment:
        Variables:
          ExpensesTable: !Ref ExpensesTable

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref ExpensesTable
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
  GetExpensesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: code/
      Handler: expenses.get
      Runtime: python3.7
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref ExpensesTable
      Events:
        GetExpenses:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /expenses
            Method: get
  PostExpensesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: code/
      Handler: expenses.post
      Runtime: python3.7
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref ExpensesTable
      Events:
        GetExpenses:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /expenses
            Method: post

  ExpensesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "ExpensesTable"
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S
        -
          AttributeName: name
          AttributeType: S
      KeySchema:
        -
          AttributeName: id
          KeyType: HASH
        -
          AttributeName: name
          KeyType: RANGE

      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: false


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  ExpensesTable:
    Value: !Ref ExpensesTable
